"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['xCodea.py']
DATA_FILES = []
OPTIONS = {'argv_emulation': True,
    'plist': {
    	'CFBundleIdentifier': 'com.marklowne.xCodea',
        'LSUIElement': True,
    },
    'packages': ['rumps'],
   }

setup(
	name='xCodea',
	author = 'Mark Lowne',
	version = '0.1',
	url = 'http://github.com/lowne/xCodea',
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
